# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EpicsPV(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EpicsPV()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEpicsPV(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EpicsPVBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x31", size_prefixed=size_prefixed)

    # EpicsPV
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EpicsPV
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EpicsPV
    def PvType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpicsPV
    def Pv(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # EpicsPV
    def TimeStamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from BrightnESS.FlatBufs.f141_epics_nt.timeStamp_t import timeStamp_t
            obj = timeStamp_t()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EpicsPV
    def Fwdinfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from BrightnESS.FlatBufs.f141_epics_nt.fwdinfo_t import fwdinfo_t
            obj = fwdinfo_t()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EpicsPV
    def Fwdinfo2Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpicsPV
    def Fwdinfo2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EpicsPVStart(builder):
    builder.StartObject(7)

def Start(builder):
    EpicsPVStart(builder)

def EpicsPVAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    EpicsPVAddName(builder, name)

def EpicsPVAddPvType(builder, pvType):
    builder.PrependUint8Slot(1, pvType, 0)

def AddPvType(builder, pvType):
    EpicsPVAddPvType(builder, pvType)

def EpicsPVAddPv(builder, pv):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pv), 0)

def AddPv(builder, pv):
    EpicsPVAddPv(builder, pv)

def EpicsPVAddTimeStamp(builder, timeStamp):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0)

def AddTimeStamp(builder, timeStamp):
    EpicsPVAddTimeStamp(builder, timeStamp)

def EpicsPVAddFwdinfo(builder, fwdinfo):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(fwdinfo), 0)

def AddFwdinfo(builder, fwdinfo):
    EpicsPVAddFwdinfo(builder, fwdinfo)

def EpicsPVAddFwdinfo2Type(builder, fwdinfo2Type):
    builder.PrependUint8Slot(5, fwdinfo2Type, 0)

def AddFwdinfo2Type(builder, fwdinfo2Type):
    EpicsPVAddFwdinfo2Type(builder, fwdinfo2Type)

def EpicsPVAddFwdinfo2(builder, fwdinfo2):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(fwdinfo2), 0)

def AddFwdinfo2(builder, fwdinfo2):
    EpicsPVAddFwdinfo2(builder, fwdinfo2)

def EpicsPVEnd(builder):
    return builder.EndObject()

def End(builder):
    return EpicsPVEnd(builder)
