# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NTScalarShort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarShort()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarShort(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NTScalarShortBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x31", size_prefixed=size_prefixed)

    # NTScalarShort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarShort
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def NTScalarShortStart(builder):
    builder.StartObject(1)

def Start(builder):
    NTScalarShortStart(builder)

def NTScalarShortAddValue(builder, value):
    builder.PrependInt16Slot(0, value, 0)

def AddValue(builder, value):
    NTScalarShortAddValue(builder, value)

def NTScalarShortEnd(builder):
    return builder.EndObject()

def End(builder):
    return NTScalarShortEnd(builder)
