# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NTScalarULong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarULong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarULong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NTScalarULongBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x31", size_prefixed=size_prefixed)

    # NTScalarULong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarULong
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def NTScalarULongStart(builder):
    builder.StartObject(1)

def Start(builder):
    NTScalarULongStart(builder)

def NTScalarULongAddValue(builder, value):
    builder.PrependUint64Slot(0, value, 0)

def AddValue(builder, value):
    NTScalarULongAddValue(builder, value)

def NTScalarULongEnd(builder):
    return builder.EndObject()

def End(builder):
    return NTScalarULongEnd(builder)
