# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NTScalarUShort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarUShort()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarUShort(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NTScalarUShortBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x31", size_prefixed=size_prefixed)

    # NTScalarUShort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarUShort
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def NTScalarUShortStart(builder):
    builder.StartObject(1)

def Start(builder):
    NTScalarUShortStart(builder)

def NTScalarUShortAddValue(builder, value):
    builder.PrependUint16Slot(0, value, 0)

def AddValue(builder, value):
    NTScalarUShortAddValue(builder, value)

def NTScalarUShortEnd(builder):
    return builder.EndObject()

def End(builder):
    return NTScalarUShortEnd(builder)
