# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NTScalarArrayShort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarArrayShort()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarArrayShort(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NTScalarArrayShortBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x31", size_prefixed=size_prefixed)

    # NTScalarArrayShort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarArrayShort
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # NTScalarArrayShort
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int16Flags, o)
        return 0

    # NTScalarArrayShort
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTScalarArrayShort
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def NTScalarArrayShortStart(builder):
    builder.StartObject(1)

def Start(builder):
    NTScalarArrayShortStart(builder)

def NTScalarArrayShortAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    NTScalarArrayShortAddValue(builder, value)

def NTScalarArrayShortStartValueVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartValueVector(builder, numElems):
    return NTScalarArrayShortStartValueVector(builder, numElems)

def NTScalarArrayShortEnd(builder):
    return builder.EndObject()

def End(builder):
    return NTScalarArrayShortEnd(builder)
