# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB_Tables

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NDArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NDArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNDArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NDArrayBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x44\x41\x72", size_prefixed=size_prefixed)

    # NDArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NDArray
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NDArray
    def TimeStamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # NDArray
    def EpicsTs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from FB_Tables.epicsTimeStamp import epicsTimeStamp
            obj = epicsTimeStamp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NDArray
    def Dims(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # NDArray
    def DimsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # NDArray
    def DimsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NDArray
    def DimsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # NDArray
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # NDArray
    def PData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # NDArray
    def PDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # NDArray
    def PDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NDArray
    def PDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # NDArray
    def PAttributeList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FB_Tables.NDAttribute import NDAttribute
            obj = NDAttribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NDArray
    def PAttributeListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NDArray
    def PAttributeListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def NDArrayStart(builder):
    builder.StartObject(7)

def Start(builder):
    NDArrayStart(builder)

def NDArrayAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    NDArrayAddId(builder, id)

def NDArrayAddTimeStamp(builder, timeStamp):
    builder.PrependFloat64Slot(1, timeStamp, 0.0)

def AddTimeStamp(builder, timeStamp):
    NDArrayAddTimeStamp(builder, timeStamp)

def NDArrayAddEpicsTs(builder, epicsTs):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(epicsTs), 0)

def AddEpicsTs(builder, epicsTs):
    NDArrayAddEpicsTs(builder, epicsTs)

def NDArrayAddDims(builder, dims):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(dims), 0)

def AddDims(builder, dims):
    NDArrayAddDims(builder, dims)

def NDArrayStartDimsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartDimsVector(builder, numElems):
    return NDArrayStartDimsVector(builder, numElems)

def NDArrayAddDataType(builder, dataType):
    builder.PrependInt8Slot(4, dataType, 0)

def AddDataType(builder, dataType):
    NDArrayAddDataType(builder, dataType)

def NDArrayAddPData(builder, pData):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(pData), 0)

def AddPData(builder, pData):
    NDArrayAddPData(builder, pData)

def NDArrayStartPDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPDataVector(builder, numElems):
    return NDArrayStartPDataVector(builder, numElems)

def NDArrayAddPAttributeList(builder, pAttributeList):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(pAttributeList), 0)

def AddPAttributeList(builder, pAttributeList):
    NDArrayAddPAttributeList(builder, pAttributeList)

def NDArrayStartPAttributeListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPAttributeListVector(builder, numElems):
    return NDArrayStartPAttributeListVector(builder, numElems)

def NDArrayEnd(builder):
    return builder.EndObject()

def End(builder):
    return NDArrayEnd(builder)
