# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class ISISData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ISISData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsISISData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ISISDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x69\x73\x38\x34", size_prefixed=size_prefixed)

    # ISISData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ISISData
    def PeriodNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ISISData
    def RunState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ISISData
    def ProtonCharge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


def ISISDataStart(builder):
    builder.StartObject(3)


def Start(builder):
    ISISDataStart(builder)


def ISISDataAddPeriodNumber(builder, periodNumber):
    builder.PrependUint32Slot(0, periodNumber, 0)


def AddPeriodNumber(builder, periodNumber):
    ISISDataAddPeriodNumber(builder, periodNumber)


def ISISDataAddRunState(builder, runState):
    builder.PrependInt8Slot(1, runState, 0)


def AddRunState(builder, runState):
    ISISDataAddRunState(builder, runState)


def ISISDataAddProtonCharge(builder, protonCharge):
    builder.PrependFloat32Slot(2, protonCharge, 0.0)


def AddProtonCharge(builder, protonCharge):
    ISISDataAddProtonCharge(builder, protonCharge)


def ISISDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return ISISDataEnd(builder)
