# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

class F(object):
    NONE = 0
    pvByte = 1
    pvShort = 2
    pvInt = 3
    pvLong = 4
    pvUByte = 5
    pvUShort = 6
    pvUInt = 7
    pvULong = 8
    pvFloat = 9
    pvDouble = 10
    pvString = 11
    pvByte_a = 12
    pvShort_a = 13
    pvInt_a = 14
    pvLong_a = 15
    pvUByte_a = 16
    pvUShort_a = 17
    pvUInt_a = 18
    pvULong_a = 19
    pvFloat_a = 20
    pvDouble_a = 21
    pvString_a = 22
    Obj = 23
    Obj_a = 24
