# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Obj_a(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Obj_a()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObj_a(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Obj_aBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x30", size_prefixed=size_prefixed)

    # Obj_a
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Obj_a
    def V(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from BrightnESS.FlatBufs.f140_general.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Obj_a
    def VLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Obj_a
    def VIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Obj_aStart(builder):
    builder.StartObject(1)

def Start(builder):
    Obj_aStart(builder)

def Obj_aAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def AddV(builder, v):
    Obj_aAddV(builder, v)

def Obj_aStartVVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVVector(builder, numElems):
    return Obj_aStartVVector(builder, numElems)

def Obj_aEnd(builder):
    return builder.EndObject()

def End(builder):
    return Obj_aEnd(builder)
