# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PV(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PV()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPV(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PVBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x30", size_prefixed=size_prefixed)

    # PV
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PV
    def N(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PV
    def VType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PV
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # PV
    def Fwdinfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from BrightnESS.FlatBufs.f140_general.fwdinfo_t import fwdinfo_t
            obj = fwdinfo_t()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PVStart(builder):
    builder.StartObject(4)

def Start(builder):
    PVStart(builder)

def PVAddN(builder, n):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(n), 0)

def AddN(builder, n):
    PVAddN(builder, n)

def PVAddVType(builder, vType):
    builder.PrependUint8Slot(1, vType, 0)

def AddVType(builder, vType):
    PVAddVType(builder, vType)

def PVAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def AddV(builder, v):
    PVAddV(builder, v)

def PVAddFwdinfo(builder, fwdinfo):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(fwdinfo), 0)

def AddFwdinfo(builder, fwdinfo):
    PVAddFwdinfo(builder, fwdinfo)

def PVEnd(builder):
    return builder.EndObject()

def End(builder):
    return PVEnd(builder)
