# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class pvByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvByte()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAspvByte(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def pvByteBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x30", size_prefixed=size_prefixed)

    # pvByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvByte
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def pvByteStart(builder):
    builder.StartObject(1)

def Start(builder):
    pvByteStart(builder)

def pvByteAddV(builder, v):
    builder.PrependInt8Slot(0, v, 0)

def AddV(builder, v):
    pvByteAddV(builder, v)

def pvByteEnd(builder):
    return builder.EndObject()

def End(builder):
    return pvByteEnd(builder)
