# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class pvUByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvUByte()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAspvUByte(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def pvUByteBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x30", size_prefixed=size_prefixed)

    # pvUByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvUByte
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def pvUByteStart(builder):
    builder.StartObject(1)

def Start(builder):
    pvUByteStart(builder)

def pvUByteAddV(builder, v):
    builder.PrependUint8Slot(0, v, 0)

def AddV(builder, v):
    pvUByteAddV(builder, v)

def pvUByteEnd(builder):
    return builder.EndObject()

def End(builder):
    return pvUByteEnd(builder)
