# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class pvUInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvUInt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAspvUInt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def pvUIntBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x30", size_prefixed=size_prefixed)

    # pvUInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvUInt
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def pvUIntStart(builder):
    builder.StartObject(1)

def Start(builder):
    pvUIntStart(builder)

def pvUIntAddV(builder, v):
    builder.PrependUint32Slot(0, v, 0)

def AddV(builder, v):
    pvUIntAddV(builder, v)

def pvUIntEnd(builder):
    return builder.EndObject()

def End(builder):
    return pvUIntEnd(builder)
