# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f143_structure

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Obj(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Obj()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObj(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ObjBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x33", size_prefixed=size_prefixed)

    # Obj
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Obj
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from f143_structure.ObjM import ObjM
            obj = ObjM()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Obj
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Obj
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ObjStart(builder):
    builder.StartObject(1)

def Start(builder):
    ObjStart(builder)

def ObjAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    ObjAddValue(builder, value)

def ObjStartValueVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartValueVector(builder, numElems):
    return ObjStartValueVector(builder, numElems)

def ObjEnd(builder):
    return builder.EndObject()

def End(builder):
    return ObjEnd(builder)
