# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f143_structure

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Structure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Structure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStructure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StructureBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x33", size_prefixed=size_prefixed)

    # Structure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Structure
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Structure
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Structure
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Structure
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Structure
    def FwdinfoType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Structure
    def Fwdinfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def StructureStart(builder):
    builder.StartObject(6)

def Start(builder):
    StructureStart(builder)

def StructureAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    StructureAddName(builder, name)

def StructureAddValueType(builder, valueType):
    builder.PrependUint8Slot(1, valueType, 0)

def AddValueType(builder, valueType):
    StructureAddValueType(builder, valueType)

def StructureAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    StructureAddValue(builder, value)

def StructureAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(3, timestamp, 0)

def AddTimestamp(builder, timestamp):
    StructureAddTimestamp(builder, timestamp)

def StructureAddFwdinfoType(builder, fwdinfoType):
    builder.PrependUint8Slot(4, fwdinfoType, 0)

def AddFwdinfoType(builder, fwdinfoType):
    StructureAddFwdinfoType(builder, fwdinfoType)

def StructureAddFwdinfo(builder, fwdinfo):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(fwdinfo), 0)

def AddFwdinfo(builder, fwdinfo):
    StructureAddFwdinfo(builder, fwdinfo)

def StructureEnd(builder):
    return builder.EndObject()

def End(builder):
    return StructureEnd(builder)
