# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f143_structure

class Value(object):
    NONE = 0
    Byte = 1
    Short = 2
    Int = 3
    Long = 4
    UByte = 5
    UShort = 6
    UInt = 7
    ULong = 8
    Float = 9
    Double = 10
    String = 11
    Obj = 12
    ArrayByte = 13
    ArrayShort = 14
    ArrayInt = 15
    ArrayLong = 16
    ArrayUByte = 17
    ArrayUShort = 18
    ArrayUInt = 19
    ArrayULong = 20
    ArrayFloat = 21
    ArrayDouble = 22
    ArrayString = 23
    ArrayObj = 24
