# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Alarm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Alarm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAlarm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AlarmBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x6C\x30\x30", size_prefixed=size_prefixed)

    # Alarm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Alarm
    def SourceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Alarm
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Alarm
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Alarm
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AlarmStart(builder):
    builder.StartObject(4)

def Start(builder):
    AlarmStart(builder)

def AlarmAddSourceName(builder, sourceName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0)

def AddSourceName(builder, sourceName):
    AlarmAddSourceName(builder, sourceName)

def AlarmAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    AlarmAddTimestamp(builder, timestamp)

def AlarmAddSeverity(builder, severity):
    builder.PrependInt16Slot(2, severity, 0)

def AddSeverity(builder, severity):
    AlarmAddSeverity(builder, severity)

def AlarmAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    AlarmAddMessage(builder, message)

def AlarmEnd(builder):
    return builder.EndObject()

def End(builder):
    return AlarmEnd(builder)
