# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# pylint: skip-file
class CacheEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CacheEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCacheEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CacheEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x6E\x73\x31\x30", size_prefixed=size_prefixed)

    # CacheEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CacheEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CacheEntry
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CacheEntry
    def Ttl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CacheEntry
    def Expired(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CacheEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CacheEntryStart(builder):
    builder.StartObject(5)

def Start(builder):
    CacheEntryStart(builder)

def CacheEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    CacheEntryAddKey(builder, key)

def CacheEntryAddTime(builder, time):
    builder.PrependFloat64Slot(1, time, 0.0)

def AddTime(builder, time):
    CacheEntryAddTime(builder, time)

def CacheEntryAddTtl(builder, ttl):
    builder.PrependFloat64Slot(2, ttl, 0.0)

def AddTtl(builder, ttl):
    CacheEntryAddTtl(builder, ttl)

def CacheEntryAddExpired(builder, expired):
    builder.PrependBoolSlot(3, expired, 0)

def AddExpired(builder, expired):
    CacheEntryAddExpired(builder, expired)

def CacheEntryAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    CacheEntryAddValue(builder, value)

def CacheEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return CacheEntryEnd(builder)
