# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class f144_LogData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = f144_LogData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsf144_LogData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def f144_LogDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x34", size_prefixed=size_prefixed)

    # f144_LogData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # f144_LogData
    def SourceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # f144_LogData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # f144_LogData
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # f144_LogData
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def f144_LogDataStart(builder):
    builder.StartObject(4)

def Start(builder):
    f144_LogDataStart(builder)

def f144_LogDataAddSourceName(builder, sourceName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0)

def AddSourceName(builder, sourceName):
    f144_LogDataAddSourceName(builder, sourceName)

def f144_LogDataAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    f144_LogDataAddTimestamp(builder, timestamp)

def f144_LogDataAddValueType(builder, valueType):
    builder.PrependUint8Slot(2, valueType, 0)

def AddValueType(builder, valueType):
    f144_LogDataAddValueType(builder, valueType)

def f144_LogDataAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    f144_LogDataAddValue(builder, value)

def f144_LogDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return f144_LogDataEnd(builder)
