# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class fwdinfo_1_t(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = fwdinfo_1_t()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsfwdinfo_1_t(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def fwdinfo_1_tBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x77\x64\x69", size_prefixed=size_prefixed)

    # fwdinfo_1_t
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # fwdinfo_1_t
    def SeqData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_1_t
    def SeqFwd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_1_t
    def TsData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_1_t
    def TsFwd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_1_t
    def Fwdix(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_1_t
    def Teamid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def fwdinfo_1_tStart(builder):
    builder.StartObject(6)

def Start(builder):
    fwdinfo_1_tStart(builder)

def fwdinfo_1_tAddSeqData(builder, seqData):
    builder.PrependUint64Slot(0, seqData, 0)

def AddSeqData(builder, seqData):
    fwdinfo_1_tAddSeqData(builder, seqData)

def fwdinfo_1_tAddSeqFwd(builder, seqFwd):
    builder.PrependUint64Slot(1, seqFwd, 0)

def AddSeqFwd(builder, seqFwd):
    fwdinfo_1_tAddSeqFwd(builder, seqFwd)

def fwdinfo_1_tAddTsData(builder, tsData):
    builder.PrependUint64Slot(2, tsData, 0)

def AddTsData(builder, tsData):
    fwdinfo_1_tAddTsData(builder, tsData)

def fwdinfo_1_tAddTsFwd(builder, tsFwd):
    builder.PrependUint64Slot(3, tsFwd, 0)

def AddTsFwd(builder, tsFwd):
    fwdinfo_1_tAddTsFwd(builder, tsFwd)

def fwdinfo_1_tAddFwdix(builder, fwdix):
    builder.PrependUint32Slot(4, fwdix, 0)

def AddFwdix(builder, fwdix):
    fwdinfo_1_tAddFwdix(builder, fwdix)

def fwdinfo_1_tAddTeamid(builder, teamid):
    builder.PrependUint64Slot(5, teamid, 0)

def AddTeamid(builder, teamid):
    fwdinfo_1_tAddTeamid(builder, teamid)

def fwdinfo_1_tEnd(builder):
    return builder.EndObject()

def End(builder):
    return fwdinfo_1_tEnd(builder)
