# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GEMHist(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GEMHist()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGEMHist(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GEMHistBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x6D\x6F\x30\x31", size_prefixed=size_prefixed)

    # GEMHist
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GEMHist
    def Xstrips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GEMHist
    def XstripsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # GEMHist
    def XstripsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GEMHist
    def XstripsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # GEMHist
    def Ystrips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GEMHist
    def YstripsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # GEMHist
    def YstripsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GEMHist
    def YstripsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GEMHist
    def Xspectrum(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GEMHist
    def XspectrumAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # GEMHist
    def XspectrumLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GEMHist
    def XspectrumIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GEMHist
    def Yspectrum(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GEMHist
    def YspectrumAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # GEMHist
    def YspectrumLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GEMHist
    def YspectrumIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # GEMHist
    def ClusterSpectrum(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GEMHist
    def ClusterSpectrumAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # GEMHist
    def ClusterSpectrumLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GEMHist
    def ClusterSpectrumIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # GEMHist
    def BinWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def GEMHistStart(builder):
    builder.StartObject(6)

def Start(builder):
    GEMHistStart(builder)

def GEMHistAddXstrips(builder, xstrips):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(xstrips), 0)

def AddXstrips(builder, xstrips):
    GEMHistAddXstrips(builder, xstrips)

def GEMHistStartXstripsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartXstripsVector(builder, numElems):
    return GEMHistStartXstripsVector(builder, numElems)

def GEMHistAddYstrips(builder, ystrips):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ystrips), 0)

def AddYstrips(builder, ystrips):
    GEMHistAddYstrips(builder, ystrips)

def GEMHistStartYstripsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartYstripsVector(builder, numElems):
    return GEMHistStartYstripsVector(builder, numElems)

def GEMHistAddXspectrum(builder, xspectrum):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(xspectrum), 0)

def AddXspectrum(builder, xspectrum):
    GEMHistAddXspectrum(builder, xspectrum)

def GEMHistStartXspectrumVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartXspectrumVector(builder, numElems):
    return GEMHistStartXspectrumVector(builder, numElems)

def GEMHistAddYspectrum(builder, yspectrum):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(yspectrum), 0)

def AddYspectrum(builder, yspectrum):
    GEMHistAddYspectrum(builder, yspectrum)

def GEMHistStartYspectrumVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartYspectrumVector(builder, numElems):
    return GEMHistStartYspectrumVector(builder, numElems)

def GEMHistAddClusterSpectrum(builder, clusterSpectrum):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(clusterSpectrum), 0)

def AddClusterSpectrum(builder, clusterSpectrum):
    GEMHistAddClusterSpectrum(builder, clusterSpectrum)

def GEMHistStartClusterSpectrumVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartClusterSpectrumVector(builder, numElems):
    return GEMHistStartClusterSpectrumVector(builder, numElems)

def GEMHistAddBinWidth(builder, binWidth):
    builder.PrependUint32Slot(5, binWidth, 0)

def AddBinWidth(builder, binWidth):
    GEMHistAddBinWidth(builder, binWidth)

def GEMHistEnd(builder):
    return builder.EndObject()

def End(builder):
    return GEMHistEnd(builder)
