# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class pos(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pos()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAspos(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def posBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x6D\x6F\x30\x31", size_prefixed=size_prefixed)

    # pos
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pos
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # pos
    def Strip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # pos
    def Adc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def posStart(builder):
    builder.StartObject(3)

def Start(builder):
    posStart(builder)

def posAddTime(builder, time):
    builder.PrependUint16Slot(0, time, 0)

def AddTime(builder, time):
    posAddTime(builder, time)

def posAddStrip(builder, strip):
    builder.PrependUint16Slot(1, strip, 0)

def AddStrip(builder, strip):
    posAddStrip(builder, strip)

def posAddAdc(builder, adc):
    builder.PrependUint16Slot(2, adc, 0)

def AddAdc(builder, adc):
    posAddAdc(builder, adc)

def posEnd(builder):
    return builder.EndObject()

def End(builder):
    return posEnd(builder)
