# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RunInfoBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x62\x61\x35\x37", size_prefixed=size_prefixed)

    # RunInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunInfo
    def InfoTypeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RunInfo
    def InfoType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RunInfoStart(builder):
    builder.StartObject(2)

def Start(builder):
    RunInfoStart(builder)

def RunInfoAddInfoTypeType(builder, infoTypeType):
    builder.PrependUint8Slot(0, infoTypeType, 0)

def AddInfoTypeType(builder, infoTypeType):
    RunInfoAddInfoTypeType(builder, infoTypeType)

def RunInfoAddInfoType(builder, infoType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(infoType), 0)

def AddInfoType(builder, infoType):
    RunInfoAddInfoType(builder, infoType)

def RunInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunInfoEnd(builder)
