# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunStop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunStop()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunStop(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RunStopBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x62\x61\x35\x37", size_prefixed=size_prefixed)

    # RunStop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunStop
    def StopTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RunStop
    def RunNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RunStopStart(builder):
    builder.StartObject(2)

def Start(builder):
    RunStopStart(builder)

def RunStopAddStopTime(builder, stopTime):
    builder.PrependUint64Slot(0, stopTime, 0)

def AddStopTime(builder, stopTime):
    RunStopAddStopTime(builder, stopTime)

def RunStopAddRunNumber(builder, runNumber):
    builder.PrependInt32Slot(1, runNumber, 0)

def AddRunNumber(builder, runNumber):
    RunStopAddRunNumber(builder, runNumber)

def RunStopEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunStopEnd(builder)
