# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class Value(object):
    NONE = 0
    Object = 1
    Bool = 2
    Long = 3
    Double = 4
    String = 5
    Dict = 6
    Array = 7
